# Data Cleaning Process

I use 16,495 U.S. job postings from 307 S&P 1,500 firms. The job-posting data come from Techmap and were collected between March 1 and March 9, 2022. Firm-level financial data come from Wharton Research Data Services (WRDS) and provide ROA in 2020 and 2021.

Before creating embeddings, I remove firm names and common aliases, URLs, and email addresses to reduce firm-identity leakage. I then split the data into train, validation, and holdout sets at the firm level so that postings from the same firm are not shared across splits.

I considered removing job titles as a robustness check (labeled as an option in the first cell). However, occupation remains inferable from responsibilities, skills, certifications, and industry-specific language, so removing the title does not eliminate occupational composition.

In [2]:
import pandas as pd
import re

# Load data
df = pd.read_csv("/Users/jiaoweigong/Desktop/HypotheSAEs/demo_data/JobPosting_2022Mar1-9.csv")

# Common firm aliases to remove from posting text.
# I used Codex to help generate/check likely aliases based on company names.
FIRM_ALIASES = {
    "advance auto parts": ["Advance Auto Parts"],
    "tjx": ["The TJX Companies", "TJX Companies", "TJX"],
    "bank of america": ["Bank of America", "BofA"],
    "marten transport": ["Marten Transport"],
    "stepan": ["Stepan Company", "Stepan Co", "Stepan"],
    "cracker barrel": ["Cracker Barrel Old Country Store", "Cracker Barrel"],
    "healthcare services group": ["Healthcare Services Group"],
    "pnc financial": ["The PNC Financial Services Group", "PNC Financial Services Group", "PNC Financial Services", "PNC"],
    "dick's sporting goods": ["DICK'S Sporting Goods", "Dicks Sporting Goods"],
    "coca-cola consolidated": ["Coca-Cola Consolidated", "Coca Cola Consolidated"],
    "marriott vacations worldwide": ["Marriott Vacations Worldwide"],
    "flowserve": ["Flowserve Corporation", "Flowserve"],
    "arrow electronics": ["Arrow Electronics"],
    "exelon": ["Exelon Corporation", "Exelon"],
    "hilton grand vacations": ["Hilton Grand Vacations"],
    "sherwin-williams": ["The Sherwin-Williams Company", "Sherwin-Williams Company", "Sherwin-Williams", "Sherwin Williams"],
    "option care health": ["Option Care Health"],
    "paychex": ["Paychex Inc", "Paychex"],
    "pg&e": ["PG&E Corporation", "PG&E", "Pacific Gas and Electric"],
    "avis budget": ["Avis Budget Group", "Avis Budget"],
    "united natural foods": ["United Natural Foods", "UNFI"],
    "eaton": ["Eaton Corporation", "Eaton"],
    "hca healthcare": ["HCA Healthcare", "HCA"],
    "chipotle": ["Chipotle Mexican Grill", "Chipotle"],
    "southern company": ["Southern Company", "The Southern Company"],
    "lowe": ["Lowe's Companies", "Lowes Companies", "Lowe's", "Lowes"],
    "colgate-palmolive": ["Colgate-Palmolive Company", "Colgate-Palmolive", "Colgate Palmolive"],
    "avalonbay": ["AvalonBay Communities", "AvalonBay"],
    "morgan stanley": ["Morgan Stanley"],
    "altec industries": ["Altec Industries", "Altec"],
    "aramark": ["Aramark"],
    "trane technologies": ["Trane Technologies", "Trane"],
    "jpmorgan chase": ["JPMorgan Chase & Co", "JPMorgan Chase", "J.P. Morgan", "JP Morgan", "JPMorgan"],
    "armstrong world industries": ["Armstrong World Industries"],
    "central garden": ["Central Garden & Pet", "Central Garden and Pet"],
    "rogers corporation": ["Rogers Corporation", "Rogers"],
    "ameriprise": ["Ameriprise Financial", "Ameriprise"],
    "hanesbrands": ["Hanesbrands Inc", "Hanesbrands"],
    "lennox international": ["Lennox International", "Lennox"],
    "american electric power": ["American Electric Power Company", "American Electric Power", "AEP"],
    "hni corporation": ["HNI Corporation", "HNI"],
    "bank of new york mellon": ["Bank of New York Mellon", "The Bank of New York Mellon", "BNY Mellon"],
    "public storage": ["Public Storage"],
    "kb home": ["KB Home"],
    "cerner": ["Cerner Corporation", "Cerner"],
    "live nation": ["Live Nation Entertainment", "Live Nation"],
    "cushman": ["Cushman & Wakefield", "Cushman and Wakefield"],
    "dxp enterprises": ["DXP Enterprises", "DXP"],
    "first american financial": ["First American Financial Corporation", "First American Financial"],
    "firstenergy": ["FirstEnergy Corp", "FirstEnergy"],
    "synchrony": ["Synchrony Financial", "Synchrony"],
    "ugi": ["UGI Corporation", "UGI"],
    "northrop grumman": ["Northrop Grumman"],
    "cnh industrial": ["CNH Industrial"],
    "dominion energy": ["Dominion Energy"],
    "advanced drainage systems": ["Advanced Drainage Systems"],
    "extra space storage": ["Extra Space Storage"],
    "fox corporation": ["FOX Corporation", "Fox Corporation", "FOX"],
    "johnson": ["Johnson & Johnson", "Johnson and Johnson", "J&J"],
    "hewlett packard enterprise": ["Hewlett Packard Enterprise", "HPE"],
    "r systems": ["R Systems"],
    "indotronix international": ["Indotronix International"],
    "aecom": ["AECOM"],
    "burlington stores": ["Burlington Stores", "Burlington"],
    "rollins": ["Rollins, Inc.", "Rollins Inc", "Rollins"],
    "molina healthcare": ["Molina Healthcare", "Molina"],
    "advanced energy industries": ["Advanced Energy Industries", "Advanced Energy"],
    "cavco industries": ["Cavco Industries", "Cavco"],
    "cardinal health": ["Cardinal Health"],
    "valley national bank": ["Valley National Bank", "Valley Bank"],
    "ford motor": ["Ford Motor Company", "Ford Motor", "Ford"],
    "jack in the box": ["Jack in the Box"],
    "marsh": ["Marsh & McLennan Companies", "Marsh and McLennan Companies", "Marsh McLennan", "Marsh"],
    "maximus": ["MAXIMUS, Inc.", "MAXIMUS Inc", "MAXIMUS"],
    "wec energy": ["WEC Energy Group", "WEC Energy", "WEC"],
    "data incorporated": ["Data Incorporated"],
    "adtalem": ["Adtalem Global Education", "Adtalem"],
    "cno financial": ["CNO Financial Group", "CNO Financial", "CNO"],
    "becton": ["Becton, Dickinson & Company", "Becton Dickinson & Company", "Becton Dickinson", "BD"],
    "lumen technologies": ["Lumen Technologies", "Lumen"],
    "pc connection": ["PC Connection, Inc.", "PC Connection Inc", "PC Connection"],
    "thermo fisher scientific": ["Thermo Fisher Scientific", "Thermo Fisher"],
    "ralph lauren": ["Ralph Lauren Corporation", "Ralph Lauren"],
    "diamondback energy": ["Diamondback Energy"],
    "azz": ["AZZ Inc.", "AZZ Inc", "AZZ"],
    "performance food group": ["Performance Food Group", "PFG"],
    "walt disney": ["The Walt Disney Company", "Walt Disney Company", "Walt Disney", "Disney"],
    "magna international": ["Magna International Inc.", "Magna International", "Magna"]
}

# Normalize firm names so matching is less sensitive to punctuation.
def normalize_name(x):
    if pd.isna(x):
        return ""
    x = str(x).lower().replace("&", "and")
    x = re.sub(r"[^a-z0-9]+", " ", x)
    return re.sub(r"\s+", " ", x).strip()

# Create a simplified version of orgname by removing "(The)" and common corporate suffixes.
def simplify_orgname(org):
    if pd.isna(org):
        return ""
    org = re.sub(r"\(\s*The\s*\)", " ", str(org), flags=re.IGNORECASE)
    org = re.sub(
        r"\b(Inc|Incorporated|Corp|Corporation|Company|Companies|Co|Ltd|Limited|LLC|PLC|Holdings)\.?\b",
        " ", org, flags=re.IGNORECASE
    )
    return re.sub(r"\s+", " ", org).strip()

# Clean each job posting.
# For every posting, remove:
#   1. the exact firm name recorded in orgname,
#   2. a simplified version of that firm name,
#   3. common aliases for larger firms from FIRM_ALIASES,
#   4. URLs and email addresses.
# Longer firm names are removed first to avoid leaving partial names behind.
def clean_text(row):
    text, org = row["text"], row["orgname"]
    if pd.isna(text):
        return ""

    text = str(text)
    names_to_remove = []

    if pd.notna(org):
        full_org = str(org).strip()
        simple_org = simplify_orgname(org)
        normalized_org = normalize_name(org)

        names_to_remove.append(full_org)
        if simple_org:
            names_to_remove.append(simple_org)

        # Match the current firm to the manually checked alias dictionary.
        for firm_key, aliases in FIRM_ALIASES.items():
            if normalize_name(firm_key) in normalized_org:
                names_to_remove.extend(aliases)

    # (Optional) robustness check: Remove the job title from the posting text.
    # Left commented out in the main analysis because occupation-specific information also appears throughout responsibilities, skills, and requirements.
    #
    # jobname = row["jobname"]
    # if pd.notna(jobname):
    #     names_to_remove.append(str(jobname).strip())

    # Remove longest names first.
    for name in sorted(set(names_to_remove), key=len, reverse=True):
        if name and len(name) >= 3:
            text = re.sub(re.escape(name), " ", text, flags=re.IGNORECASE)

     # Remove URLs and email addresses.
    text = re.sub(r"https?://\S+|www\.\S+", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"\b[\w\.-]+@[\w\.-]+\.\w+\b", " ", text)

    # Collapse extra whitespace left by removed text.
    return re.sub(r"\s+", " ", text).strip()

df["text_clean"] = df.apply(clean_text, axis=1)

pd.set_option("display.max_colwidth", None)
display(df[["orgname", "jobname", "text", "text_clean"]].sample(5, random_state=123))

                                orgname  \
6497   Cracker Barrel Old Country Store
15612             The TJX Companies Inc
8664    Healthcare Services Group, Inc.
5686                Centene Corporation
8549    Healthcare Services Group, Inc.

                                       jobname  \
6497                                      Host
15612  Retail Associate Part-Time *Now Hiring*
8664                               Housekeeper
5686                 Licensed Social Worker-NJ
8549                               Housekeeper

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         text  \
6497                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Store Location: US-VA-Midlothian Overview: As a Host and hospitality expert, you’ll get to welcome our guests into the store with a smile and call their name when it’s time to eat! Responsibilities: You’ll be the first face our guests see, so you must have a “Pleasing People” attitude. As a Host, you will have flexible hours (full or part time) and the opportunity for promotion and continued development! Qualifications: You will need to be able to stand for long periods, work in a variety of environments, be expected to lift, load and carry up to 40 pounds, and work with hot and cold food items. You must be able to understand and carry out instructions while working effectively with co-workers and managers to please our guests. We’d love to get to know you! Text “ CBJOBS ” to 97211 to start your application or click “Apply for the job online” above. NOTE: Racism, either overt or perpetuated through unconscious bias, has no place at Cracker Barrel Old Country Store, and both our Mission and People Promise are firmly rooted in the principle of valuing what everyone brings to the table. Our employees work hard to ensure that our brand, which is grounded in genuine hospitality and nostalgia, represents only what is good about those things. While our décor and food may harken back to earlier times, our inclusive culture and beliefs about equality and diversity do not. Come for the biscuits and stay for the perks- Cracker Barrel offers our employees: Culture of Belonging: We believe in Family. We care about your wellbeing and your success. We foster an atmosphere where employees care for each other like family. Our employees are encouraged to be themselves, and this means we accept and celebrate our differences. Commitment to Diversity, Equity, and Inclusion: https://www.crackerbarrel.com/Diversity-and-Inclusion Top Notch Training: PAR Training program: our hourly employee training program is built to help you grow and succeed. Earn your stars and be rewarded with pay increases We have a unique role of the Employee Training Coordinator at each location and their purpose is to help you be successful in your role Cross Training- If you thrive in an environment where no day is the same, you can cross train and work in a variety of roles for your store Diverse Career Paths: Cracker Barrel values internal development- whether you want to become an Employee Training Coordinator, a Shift Leader, a Restaurant or Retail Manager, or come join us at our Home Office in Lebanon, TN to work in corporate support for our stores; we are committed to helping you reach your personal career goals. Competitive Pay and Benefits: Competitive pay based on your experience with opportunities to earn additional pay increases with the PAR Training program Paychecks weekly Flexible Schedules Health, Vision, and Dental Benefits starting on day 1 401K with company matching starting at 90 days Vacation Time 35% off restaurant and retail items Employee Stock Purchasing Program Report this job
15612  All 1,000 of our Marshalls stores embrace discovery, from designer luggage to statement shoes. Our assortment of brands is always changing, but our mission to provide the surprises that make the everyday a little more fun is unwavering. Just like working here. Everyone encourages each other and embraces the excitement that can come with change. Each shift is a new opportunity to Discover Different. Posting Notes: Marshalls Store 0220 || 2952 Golf Road || Delafield || WI || 53018 Job Summary: Responsible for delivering a highly satisfied customer experience demonstrated by engaging and interacting with all customers, embodying customer experience principals and philosophy, and maintaining a clean and organized store environment. Adheres to all operational, merchandise, and loss prevention standards. May be cross-trained to work in multiple areas of the store in order to support the needs of the business. Responsibilities: Role models established customer experience practices with internal and external customers Supports and embodies a positive store culture through honesty, integrity, and respect Accurately rings customer purchases/returns and counts change back to customer according to established operating procedures Promotes credit and loyalty programs during customer interactions Maintains and upholds merchandising philosophy and follows established merchandising procedures and standards Accurately processes and prepares merchandise for the sales floor following company procedures and standards Initiates and participates in store recovery as needed throughout the day Maintains all organizational, cleanliness, and recovery standards for the sales floor and participates in the maintenance/cleanliness of the entire store Provides and accepts ongoing recognition and constructive feedback Adheres to all labor laws, policies, and procedures Supports and participates in store shrink reduction goals and programs Participates in safety awareness and maintenance of a risk-free environment Performs other duties as assigned Requirements: Possesses excellent customer service skills Able to work a flexible schedule to support business needs Possesses strong organizational skills with attention to detail Capable of handling multiple tasks at one time Able to respond appropriately to changes in direction or unexpected situations Possesses strong communication skills Capable of lifting heavy objects with or without reasonable accommodation Works effectively with peers and supervisors to accomplish tasks Retail customer experience preferred We’re reinventing retail and helping people discover that next find that’s going to be their new signature look. You can be a part of their journey to look amazing. Our inventory is always changing and our approach is continually evolving, which means every day is another chance to Discover Different. In fact, that’s what it’s like throughout the entire TJX family, which includes TJ Maxx, HomeGoods, Sierra, and Homesense. Discover Different also means we embrace each other’s differences and unique perspectives. We consider all applicants for employment without regard to race, color, religion, gender, sexual orientation, national origin, age, disability, gender identity and expression, marital or military status. We also provide reasonable accommodations to qualified individuals with disabilities in accordance with the Americans with Disabilities Act and applicable state and local law. Posting Notes: Marshalls Store 0220 || 2952 Golf Road || Delafield || WI || 53018 Recommended Skills Attention To Detail Business Requirements Communication Coordinating Customer Experience Customer Service Apply to this job. Think you're the perfect candidate? Apply on company site Help us improve CareerBuilder by providing feedback about this job: Report this job Job ID: 1579701 CareerBuilder TIP For your privacy and protection, when applying to a job online, never give your social security number to a prospective employer, provide credit card or bank account information, or perform any sort of monetary transaction. Learn more. By applying to a job using CareerBuilder you are agreeing to comply with and be subject to the CareerBuilder Terms and Conditions for use of our website. To use our website, you must agree with the Terms and Conditions and both meet and comply with their provisions.
8664                                                                                          Housekeeper US-MN-SAINT PAUL Requisition ID: 2022-350562 Shift: 1st Shift/Day Shift Overview Healthcare Services Group (HCSG) services thousands of accounts nationwide and is now hiring a Light Housekeeper in your area! With a custom, state of the art training program, there are engaging opportunities regardless of where you are in your career. If you crave to learn and want to make a positive impact in your community, we'd love to have you on our team! What We Offer! Free Telemedicine and Prescription discounts Comprehensive Health Coverage Paid Holidays and Vacation for eligible employees Employee Stock Purchase Plan (ESPP) available Transfers available Nationwide. Great for active Military and Family! Employee Assistance Programs Position Summary Utilizes protective gear in all appropriate functions Performs housekeeping and cleaning activities within well established guidelines and assigned areas and shift(s) to ensure that quality standards, safety guidelines and customer service expectations are met. The light housekeeper is responsible for satisfactory and timely completion of assigned cleaning area according to schedule. Reports equipment/cleaning product needs and or malfunctions to supervisor in a timely fashion. The light housekeeper performs a variety of tasks, such as dust mopping and damp mopping floors in all areas including entry ways, corridors, etc. Is responsible for the safe and proper mixing and use of cleaning solutions and adheres to all safety precautions. Cleans and sanitizes bathrooms including sinks, tubs, floors and commodes. Is responsible for the daily cleaning and sanitizing of patient room furniture, as well as sitting room and dining room furniture. Removes and disposes of trash and relieves laundry staff as needed, and performs all other related duties as assigned. Represents HCSG in a positive manner; is able to follow oral instructions, is pleasant, tactful and courteous and cooperative with supervisor, co-workers and client staff Interacts appropriately with residents, client, other personnel, supervisor and the public. Responds to customer preferences, complies with industry and federal and state guidelines, and meets the needs of residents. Must respond to the paging system in a timely and appropriate manner. Follows infection control and universal precautions policies and procedures to ensure that a sanitary environment is maintained at all times. Follow proper reporting, isolation and handwashing procedures/techniques. The light housekeeper consistently embodies the characteristics necessary to drive the Company's Purpose, Vision, Values, and DNA. Qualifications A high school diploma or equivalent is preferred. Ability to follow oral and written instructions. Must be able to speak, read and write English to communicate effectively with others. Ability to cooperate with co-workers, residents, and facility staff. Willingness to perform routine, repetitive tasks on a continuous basis. After the training period is completed, must be able to accomplish all responsibilities without supervision and do so without injury to oneself or other individuals. Must be able to fully understand and complete all in-services. Must be able to be at work as schedule on time. Compliance with COVID-19 Vaccination Policies, as required by State, Local, and/or Customers. Must be able to lift/carry a maximum of 50 pounds, push/pull a maximum of 50 pounds, stand, sit, bend and walk for extended periods of time. Must be able to work around food and cleaning products. Must live in service area. No relocation costs. HCSG is one of the largest providers of environmental, dining, and nutritional services, and as such, we continually seek out motivated and professional leaders to join our team! Our firm commitment to training provides all of our associates with ample opportunity for self-improvement and professional growth. We offer equal employment opportunities (EEO) to all employees and applicants without regard to race, color, religion, sex, national origin, age, disability, or genetics. In addition to federal law requirements, HCSG complies with applicable state and local laws governing nondiscrimination in employment in every location where the company has facilities. PI167590151 Report this job

In [3]:
# Split data into train, validation, and holdout sets by firm. 
# Each firm is assigned to only one of the three sets.
from sklearn.model_selection import train_test_split

# One row per firm
firm_df = df[["orglabel", "decline"]].drop_duplicates().reset_index(drop=True)
assert df.groupby("orglabel")["decline"].nunique().max() == 1

# 70% train, 15% val, 15% holdout
trainval_firms, holdout_firms = train_test_split(
    firm_df, test_size=0.15, random_state=123, stratify=firm_df["decline"]
)

train_firms, val_firms = train_test_split(
    trainval_firms, test_size=0.15/0.85, random_state=123,
    stratify=trainval_firms["decline"]
)

train_df = df[df["orglabel"].isin(train_firms["orglabel"])].copy()
val_df = df[df["orglabel"].isin(val_firms["orglabel"])].copy()
holdout_df = df[df["orglabel"].isin(holdout_firms["orglabel"])].copy()

# HypotheSAEs inputs
texts = train_df["text_clean"].tolist()
labels = train_df["decline"].astype(int).values
val_texts = val_df["text_clean"].tolist()
holdout_texts = holdout_df["text_clean"].tolist()
holdout_labels = holdout_df["decline"].astype(int).values

# Check
print("Train:", train_df.shape, train_df["orglabel"].nunique(), "firms")
print("Val:", val_df.shape, val_df["orglabel"].nunique(), "firms")
print("Holdout:", holdout_df.shape, holdout_df["orglabel"].nunique(), "firms")

print("Overlap:",
      len(set(train_df["orglabel"]) & set(val_df["orglabel"])),
      len(set(train_df["orglabel"]) & set(holdout_df["orglabel"])),
      len(set(val_df["orglabel"]) & set(holdout_df["orglabel"])))

# Save train, validation, and holdout as JSONL
base_dir = "/Users/jiaoweigong/Desktop/HypotheSAEs/demo_data"

train_df.to_json(f"{base_dir}/JobPosting_train.json", orient="records", lines=True, force_ascii=False)
val_df.to_json(f"{base_dir}/JobPosting_val.json", orient="records", lines=True, force_ascii=False)
holdout_df.to_json(f"{base_dir}/JobPosting_holdout.json", orient="records", lines=True, force_ascii=False)

Train: (14274, 8) 214 firms
Val: (950, 8) 46 firms
Holdout: (1271, 8) 47 firms
Overlap: 0 0 0

# HypotheSAEs Quickstart

This notebook demonstrates basic usage of HypotheSAEs.
By default we use `gpt-5.2` for hypothesis generation (interpreting neurons) and `gpt-5-mini` for text annotation.

Set `OPENAI_KEY_SAE` below for OpenAI-hosted requests. If you are using a local OpenAI-compatible endpoint (for example, vLLM server mode), set `OPENAI_BASE_URL`; the key is optional for non-OpenAI hosts.

In [ ]:
%load_ext autoreload
%autoreload 2

import os
os.environ['OPENAI_KEY_SAE'] = '...'  # delete my API key for security
# os.environ['OPENAI_BASE_URL'] = 'http://127.0.0.1:8000/v1'  # Optional: local OpenAI-compatible endpoint

import numpy as np
import pandas as pd

from hypothesaes.quickstart import train_sae, interpret_sae, generate_hypotheses, evaluate_hypotheses
from hypothesaes.embedding import get_openai_embeddings, get_local_embeddings

INTERPRETER_MODEL = "gpt-5.2"
ANNOTATOR_MODEL = "gpt-5-mini"

# Optional request kwargs forwarded directly to the Responses API.
# Keep empty by default; set only what you need at call time.
# Example: INTERPRET_LLM_KWARGS = {"reasoning_effort": "low"}
INTERPRET_LLM_KWARGS = {}
ANNOTATION_LLM_KWARGS = {}

N_WORKERS_ANNOTATION = 10  # Lower if hitting API rate limits

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

**Load cleaned train and validation data**

In [28]:
current_dir = os.getcwd()
if current_dir.endswith("notebooks"):
    prefix = "../"
else:
    prefix = "./"

base_dir = os.path.join(prefix, "demo_data")
train_df = pd.read_json(os.path.join(base_dir, "JobPosting_train.json"), lines=True)
val_df = pd.read_json(os.path.join(base_dir, "JobPosting_val.json"), lines=True)

texts = train_df['text_clean'].tolist()
labels = train_df["decline"].astype(int).values
val_texts = val_df['text_clean'].tolist() # These are only used for early stopping of SAE training, so we don't need labels.

In [29]:
print(train_df.columns.tolist())
print(train_df.dtypes)

print(train_df.iloc[0])

['orgname', 'orglabel', 'jobname', 'text', 'roa2020', 'roa2021', 'decline', 'text_clean']
orgname           str
orglabel          str
jobname           str
text              str
roa2020       float64
roa2021       float64
decline         int64
text_clean        str
dtype: object
orgname                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     AAR CORP
orglabel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    AAR Corp
jobname                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Pilot FW SP ME WASS - CONUS
text          Title: Pilot FW SP ME WASS - CONUSLocation: United States-Florida-Patrick Space Force Base, PSFBJob Number: 13209SUMMARYServe as the Chief of Standards representative in interpreting and implementing the organizations Fixed Wing Aircrew Training Program (ATP) with respect to Standardization and Maintenance, globally. Maintain and manage flight records, Air Wing Information System (AWIS) entries and updates of aviation references and publications. Responsible for conducting Rotary Wing (RW) crew member training and evaluations, standardization administration, i.e., flight records, AWIS, publications and references. Monitors flight instruction to include aircraft transition training, annual proficiency reviews, and flight evaluations. This position will be located on Patrick SFB but must have ability to travel domestically and internationally up to 90 days annually at 10-30-day intervals.ESSENTIAL DUTIES AND RESPONSIBILITIESBasic Responsibilities:- Provide support and guidance of the DoS INL/A Standardization policies, procedures, and the Aircrew Training Program.- Prepare or supervise preparation of flight plans, considering such factors as altitude, terrain, weather, range, weigh, airport facilities and navigation aids.- Supervise or accomplish the aircraft preflight inspection and preparation.- Conducts pilot training and evaluations.- Conducts maintenance operational checks (MOCs), maintenance test flights, maintenance test pilot training and maintenance test pilot evaluations as required.- Ensure proper loading, distributing, and security of cargo and passengers.- Determine aircraft weight and balance is within prescribed limits.- Retain final responsibility for the logging of aircraft flight time and the filing and closing of flight plans and preparation of flight and duty time records.- Conduct the briefing of all passengers prior to each take-off or assigns duty to direct reports but retains responsibility.- Delegate functions to other direct reports but retains overall responsibility.- Performs other aviation duties as assigned.EDUCATION and/or EXPERIENCE Required:- High school diploma or GED.- FAA Commercial and Instrument Airmans Certificate Airplane (MEL).- FCC Restricted Radiotelephone Operator Permit.- Current FAA Class II Medical Certificate.- Successful completion of FAA Type Rating in the selected type required before assignment.- 1,500 total fixed wing flight hours including 500 hours of turbine multi-engine time.- Minimum 500 hours multi-engine pilot-in-command time- SP applicant requires 300 hours multi-engine instructor pilot or check pilot time.- ME applicant requires 100 hours of FW maintenance pilot time or prior designation as a military Functional Check- Pilot/Maintenance Test Pilot.- One year managing a flight training program.- Strong English speaking and written communication skill.- Host nation language proficiency per contract requirement- LATAM countries: Spanish Level 2 in both Listening and Reading (L-2/R-2). Preferred:- FAA CFI/CFII/MEI- FAA ATP ratingQualifications:QUALIFICATIONSTo perform this job successfully, an individual must be able to perform each essential duty satisfactorily. The requirements listed below are representative of the knowledge, skill, and/or ability required.CORE COMPETENCIES1. Focus on Results - Able to plan and organize work to achieve goals; achieves targeted results with minimal supervision; is accountable for own actions.2. Communications - Possess excellent verbal & written communications skills; Provides timely, well- organized verbal & written information that is audience appropriate; listens attentively to others and retains/processes information.3. Teamwork - Builds alliances, partnerships & collaboration with others including those different from him/her; deals tactfully with others; assumes helps with a variety of team roles.4. Strategic Planning & Decision-Making - Develops strategic short- & long-term plans; arranges priorities, distinguishing urgent, important and unimportant in order to meet goals & deadlines; consults & collaborates with appropriate people.5. Initiative & Innovation - Generates new ideas personally & encourage team to do the same; stays up to date on technology & approaches to work; provides creative solutions & input when faced with challenges.6. Quality & Safety - Adheres to all safety & security policies and regulations; demonstrates quality work that is accurate, thorough & efficient.AAR is an equal opportunity employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, disability or veteran status.

**Compute text embeddings for your dataset**

We'll compute text embeddings for a training set, and optionally a validation set. The validation embeddings are used for SAE eval and early-stopping during training.

Embeddings will be stored in the `emb_cache` directory (or `os.environ["EMB_CACHE_DIR"]` if you set it) using the `cache_name` parameter, so you only need to compute embeddings once.

For embeddings, you can use OpenAI (`get_openai_embeddings`) or a local sentence-transformers model (`get_local_embeddings`).

LLM inference (interpretation/annotation) uses the unified OpenAI-compatible API path. Point it to your local endpoint by setting `OPENAI_BASE_URL` when needed.

In [ ]:
import time
from openai import RateLimitError

EMBEDDER = "text-embedding-3-small" # OpenAI
# EMBEDDER = "nomic-ai/modernbert-embed-base" # Huggingface model, will run locally
CACHE_NAME = f"jobposting_{EMBEDDER}"


# I used Codex here to help optimize the embedding pipeline for API limits by processing texts in smaller chunks and retrying after rate-limit errors.
all_texts = texts + val_texts
text2embedding = {}

for i in range(0, len(all_texts), 500):
    chunk = all_texts[i:i+500]

    while True:
        try:
            result = get_openai_embeddings(
                chunk, model=EMBEDDER, batch_size=16, n_workers=1,
                cache_name=CACHE_NAME
            )
            break
        except RateLimitError:
            print("Rate limit reached. Waiting 30 seconds...")
            time.sleep(30)

    text2embedding.update(result)
    time.sleep(30)

# text2embedding = get_local_embeddings(texts + val_texts, model=EMBEDDER, batch_size=128, cache_name=CACHE_NAME)

embeddings = np.stack([text2embedding[text] for text in texts])
train_embeddings = np.stack([text2embedding[text] for text in texts])
val_embeddings = np.stack([text2embedding[text] for text in val_texts])

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 0:   0%|          | 0/32 [00:00<?, ?it/s]

API error: Error code: 429 - {'error': {'message': 'Rate limit reached for text-embedding-3-small in organization org-iMpg2C8uQw8mp4v2NZfryiVV on tokens per min (TPM): Limit 1000000, Used 985502, Requested 33541. Please try again in 1.142s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}; retrying in 3.0s... (2/3)
Saved 482 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_000.npy

Loading embedding chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Loaded 482 embeddings in 0.1s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 1:   0%|          | 0/31 [00:00<?, ?it/s]

Saved 483 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_001.npy

Loading embedding chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Loaded 965 embeddings in 0.1s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 2:   0%|          | 0/31 [00:00<?, ?it/s]

Saved 482 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_002.npy

Loading embedding chunks:   0%|          | 0/3 [00:00<?, ?it/s]

Loaded 1447 embeddings in 0.1s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 3:   0%|          | 0/30 [00:00<?, ?it/s]

Saved 473 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_003.npy

Loading embedding chunks:   0%|          | 0/4 [00:00<?, ?it/s]

Loaded 1920 embeddings in 0.1s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 4:   0%|          | 0/30 [00:00<?, ?it/s]

Saved 476 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_004.npy

Loading embedding chunks:   0%|          | 0/5 [00:00<?, ?it/s]

Loaded 2396 embeddings in 0.2s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 5:   0%|          | 0/31 [00:00<?, ?it/s]

Saved 481 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_005.npy

Loading embedding chunks:   0%|          | 0/6 [00:00<?, ?it/s]

Loaded 2877 embeddings in 0.2s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 6:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 446 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_006.npy

Loading embedding chunks:   0%|          | 0/7 [00:00<?, ?it/s]

Loaded 3323 embeddings in 0.2s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 7:   0%|          | 0/31 [00:00<?, ?it/s]

Saved 440 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_007.npy

Loading embedding chunks:   0%|          | 0/8 [00:00<?, ?it/s]

Loaded 3763 embeddings in 0.2s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 8:   0%|          | 0/26 [00:00<?, ?it/s]

Saved 372 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_008.npy

Loading embedding chunks:   0%|          | 0/9 [00:00<?, ?it/s]

Loaded 4135 embeddings in 0.2s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 9:   0%|          | 0/23 [00:00<?, ?it/s]

Saved 349 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_009.npy

Loading embedding chunks:   0%|          | 0/10 [00:00<?, ?it/s]

Loaded 4484 embeddings in 0.4s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 10:   0%|          | 0/28 [00:00<?, ?it/s]

Saved 391 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_010.npy

Loading embedding chunks:   0%|          | 0/11 [00:00<?, ?it/s]

Loaded 4875 embeddings in 0.3s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 11:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 480 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_011.npy

Loading embedding chunks:   0%|          | 0/12 [00:00<?, ?it/s]

Loaded 5355 embeddings in 0.3s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 12:   0%|          | 0/31 [00:00<?, ?it/s]

Saved 372 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_012.npy

Loading embedding chunks:   0%|          | 0/13 [00:00<?, ?it/s]

Loaded 5727 embeddings in 0.3s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 13:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 497 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_013.npy

Loading embedding chunks:   0%|          | 0/14 [00:00<?, ?it/s]

Loaded 6224 embeddings in 0.5s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 14:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 396 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_014.npy

Loading embedding chunks:   0%|          | 0/15 [00:00<?, ?it/s]

Loaded 6620 embeddings in 0.4s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 15:   0%|          | 0/31 [00:00<?, ?it/s]

Saved 477 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_015.npy

Loading embedding chunks:   0%|          | 0/16 [00:00<?, ?it/s]

Loaded 7097 embeddings in 0.4s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 16:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 407 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_016.npy

Loading embedding chunks:   0%|          | 0/17 [00:00<?, ?it/s]

Loaded 7504 embeddings in 0.4s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 17:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 489 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_017.npy

Loading embedding chunks:   0%|          | 0/18 [00:00<?, ?it/s]

Loaded 7993 embeddings in 0.6s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 18:   0%|          | 0/30 [00:00<?, ?it/s]

Saved 480 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_018.npy

Loading embedding chunks:   0%|          | 0/19 [00:00<?, ?it/s]

Loaded 8473 embeddings in 0.4s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 19:   0%|          | 0/30 [00:00<?, ?it/s]

Saved 468 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_019.npy

Loading embedding chunks:   0%|          | 0/20 [00:00<?, ?it/s]

Loaded 8941 embeddings in 0.4s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 20:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 447 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_020.npy

Loading embedding chunks:   0%|          | 0/21 [00:00<?, ?it/s]

Loaded 9388 embeddings in 0.9s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 21:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 491 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_021.npy

Loading embedding chunks:   0%|          | 0/22 [00:00<?, ?it/s]

Loaded 9879 embeddings in 0.5s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 22:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 490 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_022.npy

Loading embedding chunks:   0%|          | 0/23 [00:00<?, ?it/s]

Loaded 10369 embeddings in 0.7s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 23:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 500 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_023.npy

Loading embedding chunks:   0%|          | 0/24 [00:00<?, ?it/s]

Loaded 10869 embeddings in 0.6s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 24:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 500 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_024.npy

Loading embedding chunks:   0%|          | 0/25 [00:00<?, ?it/s]

Loaded 11369 embeddings in 1.1s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 25:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 499 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_025.npy

Loading embedding chunks:   0%|          | 0/26 [00:00<?, ?it/s]

Loaded 11868 embeddings in 0.5s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 26:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 499 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_026.npy

Loading embedding chunks:   0%|          | 0/27 [00:00<?, ?it/s]

Loaded 12367 embeddings in 0.6s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 27:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 499 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_027.npy

Loading embedding chunks:   0%|          | 0/28 [00:00<?, ?it/s]

Loaded 12866 embeddings in 0.6s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 28:   0%|          | 0/32 [00:00<?, ?it/s]

Saved 487 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_028.npy

Loading embedding chunks:   0%|          | 0/29 [00:00<?, ?it/s]

Loaded 13353 embeddings in 1.4s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 29:   0%|          | 0/31 [00:00<?, ?it/s]

Saved 453 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_029.npy

Loading embedding chunks:   0%|          | 0/30 [00:00<?, ?it/s]

Loaded 13806 embeddings in 4.4s

Processing chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Chunk 30:   0%|          | 0/14 [00:00<?, ?it/s]

Saved 173 embeddings to /Users/jiaoweigong/Desktop/HypotheSAEs/emb_cache/jobposting_text-embedding-3-small/chunk_030.npy

**Train SAE** 

We will train a Matryoshka SAE with $M=256$, $k=8$, and $\text{prefix\_lengths} = [32, 256]$.  

With the Matryoshka loss, the SAE will learn to reconstruct the input from (1) just the first 32 neurons, and (2) all 256 neurons.  
This will produce 32 coarse-grained features, and 224 finer-grained features.  

See the README for more details about selecting SAE hyperparameters.

In [37]:
checkpoint_dir = os.path.join(prefix, "checkpoints", CACHE_NAME)
sae = train_sae(embeddings=train_embeddings, val_embeddings=val_embeddings,
                M=256, K=8, matryoshka_prefix_lengths=[32, 256], 
                checkpoint_dir=checkpoint_dir)

  0%|          | 0/100 [00:00<?, ?it/s]

Early stopping triggered after 48 epochs
Saved model to ../checkpoints/jobposting_text-embedding-3-small/SAE_matryoshka_M=256_K=8_prefixes=32-256.pt

**Interpret neurons**  

Interpret a random subset of neurons in the SAE to sanity-check that the learned features, and their interpretations, seem reasonable. We generate and print labels for `n_random_neurons` neurons, and we also print out the top-activating texts for each neuron.

In [ ]:
# This instruction will be included in the neuron interpretation prompt.
# The below instructions are specific to my task.
# If you don't pass in task-specific instructions, there is a generic instruction (see src/interpret_neurons.py);
# task-specific instructions are optional, but they help produce hypotheses at the desired level of specificity.

TASK_SPECIFIC_INSTRUCTIONS = """All of the texts are job postings from firms.
Features should describe a specific aspect of the job posting language, such as job requirements, responsibilities, workplace culture, employee expectations, skills, benefits, career development, flexibility, diversity, or organizational priorities.

Avoid describing features only in terms of specific company names, brand names, or job titles. Prefer generalizable patterns in recruiting language.

For example:
- "emphasizes teamwork and collaboration"
- "stresses performance targets and measurable results"
- "highlights opportunities for promotion and career development"
- "emphasizes flexible schedules and work arrangements"
- "mentions diversity, inclusion, and belonging"
"""

results = interpret_sae(
    texts=texts,
    embeddings=train_embeddings,
    sae=sae,
    n_random_neurons=5,
    print_examples_n=3,
    task_specific_instructions=TASK_SPECIFIC_INSTRUCTIONS,
    interpreter_model=INTERPRETER_MODEL,
    interpret_llm_kwargs=INTERPRET_LLM_KWARGS,
)

Computing activations (batchsize=16384):   0%|          | 0/1 [00:00<?, ?it/s]

Activations shape: (14274, 256)

Generating interpretations:   0%|          | 0/5 [00:00<?, ?it/s]

Neuron 140 (6.1% active): explicitly references Colorado-specific job details (e.g., CO locations and/or the Colorado compensation-range disclosure language)

Top activating examples:
1. For individuals assigned and/or hired to work in Colorado, is required by law to include a reasonable estimate of the compensation for this role. This compensation range is specific to the State of Colorado and takes into account various factor Manager, Business, Development, Account, Sales, Sales Manager, Manufacturing
2. Are you ready to grow your dream career while making others' vacation dreams come true? is a world premier organization for Vacation Ownership with resorts at destinations around the globe. Join our team and help deliver unforgettable experiences that make vacation dreams come true. Hospitality Job Fair – Sheraton Mountain Vista Villas & Marriott's StreamSide All candidates are guaranteed an interview! Openings at locations in Avon and Vail, CO! $1000 Starting Bonus! Full-Time, Part-Time, Seasonal and Year-Round positions available! Wednesday, March 16th 1pm – 6pm Sheraton Mountain Vista Villas 160 W Beaver Creek Blvd, Avon, CO Please RSVP by submitting an application or resume, and we will reach out to you with your schedule time slot for the hiring event! Please be sure to check your inbox the day prior to the event for your scheduled time and specific directions on where to report the day of the event. *Masks will be required at the event* Open Positions/Status/Wage Front Desk Agent — Full-Time — $20.00/hr[... rest of text is truncated]
3. Are you ready to grow your dream career while making others' vacation dreams come true? is a world premier organization for Vacation Ownership with resorts at destinations around the globe. Join our team and help deliver unforgettable experiences that make vacation dreams come true. Colorado Sales and Marketing Career Mixer Event with Saturday, March 12th: 12pm, 2pm & 4pm Hosted Virtually for available positions based at: The Westin Riverfront Mountain Villas Sheraton Mountain Vista Villas Sheraton Steamboat Resort Villas The Ritz Carlton Club, Vail - Marriott Vacation Club Explore Your Next Career in the Vacation Ownership Industry! Are you ready to grow your dream career while making others' vacation dreams come true? is a world premier organization for Vacation Ownership with resorts at destinations around the globe. Join our team and help deliver unforgettable experiences that make vacation dreams come true. We are currently looking for driven individuals with outgoing personalities who are financially mo[... rest of text is truncated]
----------------------------------------------------------------------------------------------------

Neuron 28 (23.4% active): includes an Equal Opportunity Employer non-discrimination statement listing many protected classes (e.g., race, color, sex, age, national origin, religion, sexual orientation, gender identity, veteran status, disability) near the start of the posting

Top activating examples:
1. Job Description We are an Equal Opportunity Employer and do not discriminate against any employee or applicant for employment because of race, color, sex, age national origin, religion, sexual orientation, gender identity, status as a veteran and basis of disability or any other federal, state or local protected class. What is a Store Driver? Entry level store position capable of supporting delivery of parts to commercial customers. The role has the responsibility to deliver parts to our commercial customers and assist with task and inventory processes in the store. This position can be part time or full time and must be fleet safety certified. Primary Responsibilities • Safely deliver parts to customers as needed • Pick and stage parts for customer orders • Pick up returns and cores • Drop off weekly / monthly sales flyer • Daily collection of credit accounts Secondary Responsibilities • Store Cleanliness including floors, bathrooms, facing, dusting, parking lot • General stocking including truck stocking an[... rest of text is truncated]
2. Job Description We are an Equal Opportunity Employer and do not discriminate against any employee or applicant for employment because of race, color, sex, age national origin, religion, sexual orientation, gender identity, status as a veteran and basis of disability or any other federal, state or local protected class. What is a Store Driver? Entry level store position capable of supporting delivery of parts to commercial customers. The role has the responsibility to deliver parts to our commercial customers and assist with task and inventory processes in the store. This position can be part time or full time and must be fleet safety certified. Primary Responsibilities • Safely deliver parts to customers as needed • Pick and stage parts for customer orders • Pick up returns and cores • Drop off weekly / monthly sales flyer • Daily collection of credit accounts Secondary Responsibilities • Store Cleanliness including floors, bathrooms, facing, dusting, parking lot • General stocking including truck stocking an[... rest of text is truncated]
3. Job Description We are an Equal Opportunity Employer and do not discriminate against any employee or applicant for employment because of race, color, sex, age national origin, religion, sexual orientation, gender identity, status as a veteran and basis of disability or any other federal, state or local protected class. What is a Store Driver? Entry level store position capable of supporting delivery of parts to commercial customers. The role has the responsibility to deliver parts to our commercial customers and assist with task and inventory processes in the store. This position can be part time or full time and must be fleet safety certified. Primary Responsibilities • Safely deliver parts to customers as needed • Pick and stage parts for customer orders • Pick up returns and cores • Drop off weekly / monthly sales flyer • Daily collection of credit accounts Secondary Responsibilities • Store Cleanliness including floors, bathrooms, facing, dusting, parking lot • General stocking including truck stocking an[... rest of text is truncated]
----------------------------------------------------------------------------------------------------

Neuron 50 (2.2% active): describes freight/logistics transportation work (shipping, import/export, customs brokerage, freight forwarding, track-and-trace, warehousing) using operational terms like entries, bills of lading/documentation, carriers/brokers/forwarders, and compliance/KPI process flow

Top activating examples:
1. Job Description Operates a truck that transports cargo to and from specified destinations. Prepares, receives, and provides appropriate documentation for the delivery or pick up of goods to ensure timely service. Loads, secures, verifies, and unloads cargo. Education: Experience: Job Duties: Recommended Skills Freight Forwarding Apply to this job. Think you're the perfect candidate? Apply on company site Help us improve CareerBuilder by providing feedback about this job: Report this job Job ID: R-0235835 CareerBuilder TIP For your privacy and protection, when applying to a job online, never give your social security number to a prospective employer, provide credit card or bank account information, or perform any sort of monetary transaction. Learn more. By applying to a job using CareerBuilder you are agreeing to comply with and be subject to the CareerBuilder Terms and Conditions for use of our website. To use our website, you must agree with the Terms and Conditions and both meet and comply with their provi[... rest of text is truncated]
2. Job Description Operates a truck that transports cargo to and from specified destinations. Prepares, receives, and provides appropriate documentation for the delivery or pick up of goods to ensure timely service. Loads, secures, verifies, and unloads cargo. Education: Experience: Job Duties: Recommended Skills Freight Forwarding Apply to this job. Think you're the perfect candidate? Apply on company site Help us improve CareerBuilder by providing feedback about this job: Report this job Job ID: R-0228419 CareerBuilder TIP For your privacy and protection, when applying to a job online, never give your social security number to a prospective employer, provide credit card or bank account information, or perform any sort of monetary transaction. Learn more. By applying to a job using CareerBuilder you are agreeing to comply with and be subject to the CareerBuilder Terms and Conditions for use of our website. To use our website, you must agree with the Terms and Conditions and both meet and comply with their provi[... rest of text is truncated]
3. Job Description Operates a truck that transports cargo to and from specified destinations. Prepares, receives, and provides appropriate documentation for the delivery or pick up of goods to ensure timely service. Loads, secures, verifies, and unloads cargo. Education: Experience: Job Duties: Recommended Skills Communications Time Management Decision Making Employee Performance Management Training And Development Written Communication Apply to this job. Think you're the perfect candidate? Apply on company site Help us improve CareerBuilder by providing feedback about this job: Report this job Job ID: R-0234203 CareerBuilder TIP For your privacy and protection, when applying to a job online, never give your social security number to a prospective employer, provide credit card or bank account information, or perform any sort of monetary transaction. Learn more. By applying to a job using CareerBuilder you are agreeing to comply with and be subject to the CareerBuilder Terms and Conditions for use of our website.[... rest of text is truncated]
----------------------------------------------------------------------------------------------------

Neuron 23 (20.8% active): includes a driver referral bonus with a specific dollar amount and staged payout timeline (e.g., $2,000 paid at 3 and 9 months)

Top activating examples:
1. Now Hiring Class A Local Drivers in Dayville, CT! - Home Daily + $22/hour! Call Us Today 8559684126 Benefits: Competitive hourly wages starting at $22/hr. (paid weekly) $2,000 Referral Bonus! Refer a CDL Driver for any open roles across the US & receive a $2,000 bonus!! 1st Payout at 3 Months from referral hire date: $1,000 2nd Payout at 9 Months from referral hire date: $1,000 Paid Overtime after 40 hours worked Paid DOT break plus meal per-diem and monthly cell phone reimbursement plan Generous Paid Time Off- Drivers accrue over 4 weeks of PTO in the 1st year Paid holidays (7) per year + (1) floating holiday Safety bonus and performance award programs Home daily - great work-life balance Clean, new model, well maintained equipment-trailers equipped with lift-gates and power jacks Healthy food purchasing discount program Driver uniform program Comprehensive benefits package: Medical, Dental, Vision, Disability & Life insurance, flex spending. Profit sharing and 401(k) with company match AND MORE! Requirement[... rest of text is truncated]
2. Now Hiring Class A Local Drivers in Dayville, CT! - Home Daily + $22/hour! Call Us Today 8559684126 Benefits: Competitive hourly wages starting at $22/hr. (paid weekly) $2,000 Referral Bonus! Refer a CDL Driver for any open roles across the US & receive a $2,000 bonus!! 1st Payout at 3 Months from referral hire date: $1,000 2nd Payout at 9 Months from referral hire date: $1,000 Paid Overtime after 40 hours worked Paid DOT break plus meal per-diem and monthly cell phone reimbursement plan Generous Paid Time Off- Drivers accrue over 4 weeks of PTO in the 1st year Paid holidays (7) per year + (1) floating holiday Safety bonus and performance award programs Home daily - great work-life balance Clean, new model, well maintained equipment-trailers equipped with lift-gates and power jacks Healthy food purchasing discount program Driver uniform program Comprehensive benefits package: Medical, Dental, Vision, Disability & Life insurance, flex spending. Profit sharing and 401(k) with company match AND MORE! Requirement[... rest of text is truncated]
3. Now Hiring Class A Local Drivers in Dayville, CT! - Home Daily + $22/hour! Call Us Today 8559684126 Benefits: Competitive hourly wages starting at $22/hr. (paid weekly) $2,000 Referral Bonus! Refer a CDL Driver for any open roles across the US & receive a $2,000 bonus!! 1st Payout at 3 Months from referral hire date: $1,000 2nd Payout at 9 Months from referral hire date: $1,000 Paid Overtime after 40 hours worked Paid DOT break plus meal per-diem and monthly cell phone reimbursement plan Generous Paid Time Off- Drivers accrue over 4 weeks of PTO in the 1st year Paid holidays (7) per year + (1) floating holiday Safety bonus and performance award programs Home daily - great work-life balance Clean, new model, well maintained equipment-trailers equipped with lift-gates and power jacks Healthy food purchasing discount program Driver uniform program Comprehensive benefits package: Medical, Dental, Vision, Disability & Life insurance, flex spending. Profit sharing and 401(k) with company match AND MORE! Requirement[... rest of text is truncated]
----------------------------------------------------------------------------------------------------

Neuron 81 (1.1% active): assistant general manager job posting for an auto parts retail store that explicitly mentions providing DIY automotive services (battery testing/installation, wiper installs) along with manager-on-duty duties like scheduling and coaching team members

Top activating examples:
1. Job Description Primary Responsibilities • Provide GAS3 selling experience for DIY and professional customers • Provide leadership and developmental coaching for store Team Members • Achieve personal / store sales goals and service objectives • Manage DIY services including battery installation, testing, wiper installs, etc. • Ensure high standards of customer service including prompt handling of any complaints for product and operational standards • Understand levers to impact P&L • Manager on duty responsibilities (touch base/coaching, issue resolution, floor/phone mgmt., task assignment and completion, safety, open/close duties) • Weekly scheduling process Secondary Responsibilities • Assist in backing up operations of commercial delivery program • Provide DIY services including battery installation, testing, wiper installs, etc. Success Factors • Act like an owner • Superior communication and customer service skills • Ability to locate and stock parts • Safety knowledge and skills • Parts and automotive s[... rest of text is truncated]
2. Job Description Primary Responsibilities • Provide GAS3 selling experience for DIY and professional customers • Provide leadership and developmental coaching for store Team Members • Achieve personal / store sales goals and service objectives • Manage DIY services including battery installation, testing, wiper installs, etc. • Ensure high standards of customer service including prompt handling of any complaints for product and operational standards • Understand levers to impact P&L • Manager on duty responsibilities (touch base/coaching, issue resolution, floor/phone mgmt., task assignment and completion, safety, open/close duties) • Weekly scheduling process Secondary Responsibilities • Assist in backing up operations of commercial delivery program • Provide DIY services including battery installation, testing, wiper installs, etc. Success Factors • Act like an owner • Superior communication and customer service skills • Ability to locate and stock parts • Safety knowledge and skills • Parts and automotive s[... rest of text is truncated]
3. Job Description Primary Responsibilities • Provide GAS3 selling experience for DIY and professional customers • Provide leadership and developmental coaching for store Team Members • Achieve personal / store sales goals and service objectives • Manage DIY services including battery installation, testing, wiper installs, etc. • Ensure high standards of customer service including prompt handling of any complaints for product and operational standards • Understand levers to impact P&L • Manager on duty responsibilities (touch base/coaching, issue resolution, floor/phone mgmt., task assignment and completion, safety, open/close duties) • Weekly scheduling process Secondary Responsibilities • Assist in backing up operations of commercial delivery program • Provide DIY services including battery installation, testing, wiper installs, etc. Success Factors • Act like an owner • Superior communication and customer service skills • Ability to locate and stock parts • Safety knowledge and skills • Parts and automotive s[... rest of text is truncated]
----------------------------------------------------------------------------------------------------

**Generate hypotheses**

Generate hypotheses which are predictive of the target variable.

The `selection_method` parameter defines how we compute neuron predictiveness (see `src/select_neurons.py` for more details):
- "separation_score": E[target | top-activating examples] - E[target | zero-activating examples]
- "correlation": pearson(neuron activations, target variable)
- "lasso": select N nonzero features with an L1 regularized model

This cell outputs a dataframe with the following columns:
- `neuron_idx`: The index of the neuron in the SAE (if you're using multiple SAEs, this will be a global index across all of them).
- `source_sae`: The SAE that the neuron was selected from.
- `target_{selection_method}`: The predictiveness of the neuron for the target variable, using the selected `selection_method`.
- `interpretation`: The natural language interpretation of the neuron.
- `interp_fidelity_score`: The F1 fidelity score for how well the neuron's interpretation actually corresponds to its activation pattern.

In [39]:
selection_method = "correlation"

results = generate_hypotheses(
    texts=texts,
    labels=labels,
    embeddings=train_embeddings,
    sae=sae,
    cache_name=CACHE_NAME,
    selection_method=selection_method,
    n_selected_neurons=20,
    n_candidate_interpretations=1,
    task_specific_instructions=TASK_SPECIFIC_INSTRUCTIONS,
    interpreter_model=INTERPRETER_MODEL,
    annotator_model=ANNOTATOR_MODEL,
    interpret_llm_kwargs=INTERPRET_LLM_KWARGS,
    annotation_llm_kwargs=ANNOTATION_LLM_KWARGS,
    n_workers_annotation=N_WORKERS_ANNOTATION,
)

print("\nMost predictive features of ROA decline:")

pd.set_option("display.max_colwidth", None)
display(results.sort_values(by=f"target_{selection_method}", ascending=False).round(3))
pd.reset_option("display.max_colwidth")

Embeddings shape: (14274, 1536)

Computing activations (batchsize=16384):   0%|          | 0/1 [00:00<?, ?it/s]

Activations shape: (14274, 256)

Step 1: Selecting top 20 predictive neurons

Step 2: Interpreting selected neurons

/Users/jiaoweigong/Desktop/HypotheSAEs/hypothesaes/select_neurons.py:130: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearsonr(activations[:, i], target)[0]

Generating interpretations:   0%|          | 0/20 [00:00<?, ?it/s]

Step 3: Scoring Interpretations
Found 0 cached items; annotating 2000 uncached items

Scoring neuron interpretation fidelity (20 neurons; 1 candidate interps per neuron; 100 examples to score each…

Most predictive features of ROA decline:

,neuron_idx,target_correlation,interpretation,f1_fidelity_score
0,10,0.527,"describes front-office financial markets risk/trading technology or regulatory/compliance initiatives using domain-specific jargon (e.g., Market Risk, FRTB/IMA, VaR, KYC-AML, desk/trader workflows, margin/exposure) and end-to-end delivery artifacts like BRDs, UAT, model validation, and data quality controls",0.675
1,15,0.435,"describes corporate finance/investment banking work involving capital markets transactions and quantitative financial modeling/valuation (e.g., M&A, IPOs, debt/equity raises, swaps/derivatives, risk models, Bloomberg/FactSet) in a global financial services context",0.507
2,19,0.379,"describes retail branch banking sales behaviors like proactive outbound calling, appointment setting, lobby engagement, and using a defined sales process to deepen customer relationships and grow share of wallet",1.000
4,1,0.295,"describes a retail banking relationship-building role focused on advising clients on personal financial goals and educating them on digital banking solutions, with explicit mention of structured onboarding/training and clear internal advancement paths (e.g., Relationship Manager/Financial Advisor/branch management)",1.000
5,29,0.291,"lists extensive enterprise software architecture/engineering technical requirements (e.g., .NET/Java, cloud platforms like Azure/AWS, APIs/web services, CI/CD tools, databases) in a long skills/technology stack section",0.611
7,9,0.254,"focuses on mortgage/loan closing documentation administration (preparing/reviewing loan documents, coordinating closings, ensuring lien perfection and regulatory compliance, handling funding/booking and post-closing collateral files)",0.734
8,22,0.246,"industrial mechanical service/repair work on pumps and related equipment (e.g., dismantling/assembling pumps, welding/pipe-fitting, troubleshooting pump performance at customer sites)",0.649
10,8,0.220,"includes a standardized job header listing logistics/compliance fields like primary location, relocation offered, employment status, travel percentage, and non-compete status",0.810
15,40,0.180,"includes a standardized corporate intro slogan and branding block (e.g., 'At [company], we've got a place for you!' / 'Energize your career') followed by an all-caps 'PRIMARY PURPOSE OF POSITION' section heading",0.925
18,66,0.176,"mentions mechanical seal/turbomachinery order engineering work, including creating CAD drawings/models in SolidWorks or AutoCAD for seal components and critical dimensions",0.413
19,247,0.172,"describes an analytics/reporting role that builds dashboards or reports from data using BI/analysis tools (e.g., SQL, PowerBI/Tableau/OBIEE/Essbase) and provides metrics/KPI insights to internal stakeholders",0.837
17,26,-0.179,"includes a retail store “Posting Notes” line that lists a specific store number and full street address using double-pipe separators (e.g., “Store #### || address || city || state || zip”)",0.949
16,12,-0.180,"CDL-A trucking recruitment ad language that lists driver pay guarantees/bonuses and equipment specs (e.g., automatic transmission trucks, governed top speed, home time, layover pay) along with explicit CDL-A/age/experience qualifications",1.000
14,244,-0.183,"describes front-end retail cashiering duties, including ringing customer purchases/returns, counting change, and promoting store credit/loyalty programs during customer interactions",0.867
13,23,-0.184,driver recruiting ad that explicitly advertises being “Home daily” for local Class A CDL truck drivers,1.000
12,20,-0.194,includes the TJ Maxx recruiting slogan/brand language 'Discover Different' and describes an 'ever-changing' store environment with 'the thrill of the find',0.970
11,18,-0.212,"promotes long-haul truck driver compensation with explicit guaranteed weekly pay and home-time frequency (e.g., home weekly/every other week), often alongside sign-on/hiring bonuses and accessorial pays like detention/layover/inclement weather pay",0.990
9,4,-0.245,"describes retail auto-parts store work specifically supporting DIY customers, including in-store vehicle services like battery testing/installation and wiper installs, plus parts lookup/POS and inventory processes",1.000
6,28,-0.265,"includes a detailed Equal Opportunity Employer non-discrimination statement listing protected classes (e.g., race, color, sex, age, national origin, religion, sexual orientation, gender identity, veteran status, disability) near the start of the posting",1.000
3,5,-0.317,includes a standardized retail store posting header with 'Posting Notes' followed by a specific store number and full street address formatted with '||' separators,1.000

**Evaluate held-out generalization**

Finally, we evaluate whether these are good hypotheses by testing whether their natural language interpretations can predict the target variable.  

We compute annotations for each hypothesized concept on a holdout set (not seen during SAE training & feature selection).

After annotation, we output a dataframe with the following columns:
- `hypothesis`: The natural language hypothesis (which came from interpreting a predictive neuron in the SAE)
- `separation_score`: How much the target variable differs when the concept is present vs. absent (i.e., $E[Y\mid\text{concept} = 1] - E[Y\mid\text{concept} = 0]$).
- `separation_pvalue`: The t-test p-value of the null hypothesis that the separation score is 0 (i.e., the concept is not associated with the target variable).
- `regression_coef`: The coefficient of the concept in a multivariate linear regression of the target variable on all concepts.
- `regression_pval`: The p-value of the null hypothesis that the regression coefficient is 0.
- `feature_prevalence`: The fraction of examples that contain the concept.

Additionally, we output the evaluation metrics used in the paper:
- Significant hypotheses: the number of hypotheses that are significant in the multivariate regression at a specified significance level (default $0.1$) after Bonferroni correction. You can pass in a different significance level using the `corrected_pval_threshold` parameter.
- AUC or $R^2$: how well the hypotheses collectively predict the target variable in the multivariate regression.

In [41]:
results_3 = (
    results.assign(abs_corr=results["target_correlation"].abs())
           .sort_values("abs_corr", ascending=False)
           .head(3)
           .drop(columns="abs_corr")
)

holdout_df = pd.read_json(os.path.join(base_dir, "JobPosting_holdout.json"), lines=True)
holdout_texts = holdout_df["text_clean"].tolist()
holdout_labels = holdout_df["decline"].astype(int).values

metrics, evaluation_df = evaluate_hypotheses(
    hypotheses_df=results_3,
    texts=holdout_texts,
    labels=holdout_labels,
    cache_name=CACHE_NAME,
    annotator_model=ANNOTATOR_MODEL,
    annotation_llm_kwargs=ANNOTATION_LLM_KWARGS,
    n_workers_annotation=N_WORKERS_ANNOTATION, # Please lower this parameter if you are running into API rate limits
)

pd.set_option("display.max_colwidth", None)
display(evaluation_df.sort_values(by="separation_score", ascending=False).round(3))
pd.reset_option("display.max_colwidth")

print("\nHoldout Set Metrics:")
print(metrics)
print(f"Significant hypotheses: {metrics['Significant'][0]}/{metrics['Significant'][1]} "
      f"(p < {metrics['Significant'][2]:.3e})")

Step 1: Annotating texts with 3 hypotheses
Found 735 cached items; annotating 3078 uncached items

Annotating:   0%|          | 0/3078 [00:00<?, ?it/s]

Step 2: Computing predictiveness of hypothesis annotations
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.299890
         Iterations: 35
Error fitting model: Singular matrix, trying OLS instead

/Users/jiaoweigong/Desktop/HypotheSAEs/hypothesaes/evaluation.py:150: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  results = model.fit()
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:3862: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/jiaoweigong/Desktop/HypotheSAEs/hypothesaes/evaluation.py:118: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  _, p_value = ttest_ind(pos_vals, neg_vals)
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/scipy/stats/_axis_nan_policy.py:601: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

,hypothesis,separation_score,separation_pval,regression_coef,regression_pval,feature_prevalence
1,"describes corporate finance/investment banking work involving capital markets transactions and quantitative financial modeling/valuation (e.g., M&A, IPOs, debt/equity raises, swaps/derivatives, risk models, Bloomberg/FactSet) in a global financial services context",0.097,0.006,0.096,0.006,0.056
2,"describes retail branch banking sales behaviors like proactive outbound calling, appointment setting, lobby engagement, and using a defined sales process to deepen customer relationships and grow share of wallet",-0.052,0.635,-0.046,0.670,0.006
0,"describes front-office financial markets risk/trading technology or regulatory/compliance initiatives using domain-specific jargon (e.g., Market Risk, FRTB/IMA, VaR, KYC-AML, desk/trader workflows, margin/exposure) and end-to-end delivery artifacts like BRDs, UAT, model validation, and data quality controls",NaN,NaN,0.000,0.590,0.000

Holdout Set Metrics:
{'auroc': 0.5321839080459769, 'auprc': 0.9146102753590628, 'Significant': (1, 3, 0.03333333333333333)}
Significant hypotheses: 1/3 (p < 3.333e-02)

API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)
Failed to annotate after 3 attempts: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}
API error: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}; retrying in 2.0s... (2/3)

## Cosine-Similarity Benchmark

As a follow-up suggested in the assignment 3.b., I considered using cosine similarity as a cheaper alternative to LLM-based holdout annotation for the same three hypotheses. The code below embeds each hypothesis, compares it with the holdout-text embeddings, and examines whether the similarity scores are associated with the ROA-decline label. A fuller benchmark would also compare these cosine-similarity scores directly with the posting-level LLM annotations to assess whether the two approaches produce similar conclusions. Because I started this extension late and the notebook kernel had restarted, I did not rerun the full pipeline and leave the code below as a possible follow-up.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy.stats import pointbiserialr

hypotheses = results_3["hypothesis"].tolist()
cosine_texts = holdout_texts + hypotheses

cosine_dict = get_openai_embeddings(cosine_texts, model=EMBEDDER, batch_size=16, n_workers=1, cache_name=CACHE_NAME)

holdout_emb = np.stack([cosine_dict[x] for x in holdout_texts])
hypothesis_emb = np.stack([cosine_dict[x] for x in hypotheses])
similarities = cosine_similarity(holdout_emb, hypothesis_emb)

cosine_results = []
for j, h in enumerate(hypotheses):
    r, p = pointbiserialr(holdout_labels, similarities[:, j])
    cosine_results.append({"hypothesis": h, "correlation": r, "p_value": p,
                           "mean_similarity": similarities[:, j].mean()})

cosine_results = pd.DataFrame(cosine_results)
display(cosine_results.round(3))